spring.application.name=springboot-paypal-integration

#server.port=8443
#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=contrasenasegura
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=springboot

paypal.client-id=XXXXXXXXXXXXXXXXXXXXXXXXXXXX
paypal.client-secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXX
paypal.base-url=https://api.sandbox.paypal.com
app.subscription=29.99
app.frontend-url=http://localhost:4200